site_name: The Ivory Tower
site_description: The Ivory Tower is a blog about software engineering and development philosophy by Anders Sundman.
site_url: https://4zm.org

theme:
  name: material
  features:
    - navigation.expand
    - navigation.tabs
  logo: images/floppy-white.png

extra_css:
  - custom.css

plugins:
  - search
  - blog:
      blog_dir: .
  - offline
  - rss:
      match_path: posts/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.blocks.html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:anders@4zm.org
    - icon: fontawesome/solid/rss
      link: /feed_rss_created.xml
  analytics:
    provider: google
    property: G-HLXBBN0SQ4

copyright: Copyright &copy; 2024-2025 Anders Sundman
